language: python
python:
        - '3.8'

install:
        - pip install -r requirements-dev.txt

env:
        - PYTHONPATH=/home/travis/build/jdahhan1/PutMeOn

script:
        - make all_tests

deploy:
        - provider: heroku
          api_key: $HEROKU_API_KEY
          app: putmeon1
          on:
                  branch: master
